M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu20.04.1} date So 29 Okt 2023 13:01:42 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-29T13:01:42+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
%
G90
G05
T1
X2.089Y-1.7928
X2.089Y-1.9739
T0
M30
